# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb15f2ad380b82176195f83e8fa7ad707dcfad1d8e6fc3bb811e2ab9fd0254c88a577a938ad5213d60b98b4d44cc9fe2fb197adb1106b2bf98c7e792634f9ecc

test:
  secret_key_base: e9c4f18e7c1b7bc42b7ab54b871fb3ce8f5b663a5be1bde0d13ef860af956cd7babc0c5bb4f0816af616c28c40c41a29a8895cc83e546b3132be449a54f84419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
